// Copyright 2026 The Waveoff Authors.
// SPDX-License-Identifier: Apache-2.0

// Command gendocs renders docs/digest.md from the classification map.
//
// The map is normative, so its documentation is generated rather than written:
// a rationale that has drifted from the code it describes is worse than none,
// and this is the document a compliance reader will be handed.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/waveoffai/waveoff/internal/digest"
)

const header = `<!-- Generated by hack/gendocs from internal/digest/classify.go. Do not edit. -->

# The two digests

An ` + "`AgentManifest`" + ` carries two hashes, and they answer different questions.

| | ` + "`behaviorDigest`" + ` | ` + "`contentDigest`" + ` |
|---|---|---|
| Covers | the fields that determine behaviour | the whole spec, no exclusions |
| Answers | "is this the same agent?" | "has this record been altered?" |
| Used for | corpus keying, replay matching, deciding whether a rollout needs a canary | immutability enforcement, tamper evidence, compliance records |
| Has a classification map | yes, below | no |

Two manifests with the same ` + "`behaviorDigest`" + ` are the same agent. If their
` + "`contentDigest`" + ` differs, something was recorded that does not change what the
agent does — a registry migration, a prompt moved between repositories, a judge
whose agreement with the gold set was re-measured. A rollout between them
promotes immediately, with no canary, because there is nothing to canary.

Having both matters. Behaviour-only alone would carry a silent-collision risk —
two genuinely different specs hashing identically — and would leave half the
release record uncovered by any hash. Whole-spec alone would mint a new agent
identity for a registry move, forcing a needless canary on a change that
provably cannot alter behaviour. Because only one of the two has a
classification map, a field misclassified below is still caught by
` + "`contentDigest`" + `.

## Who computes them

You do. ` + "`waveoff pin`" + ` emits them and ` + "`waveoff verify --write`" + ` repairs them;
admission recomputes and compares, but never fills them in.

This is deliberate. A mutating webhook that wrote digests into the stored object
would leave Argo CD and Flux showing a permanent, un-reconcilable difference
between desired and live state — the classic mutating-webhook-versus-GitOps
failure, in a product that is GitOps-native. It also makes the weaker compliance
claim: a digest minted server-side at admission is not the same artifact as one
that was authored, reviewed and committed to git.

## Canonical form

Both digests are ` + "`sha256`" + ` over the [RFC 8785](https://www.rfc-editor.org/rfc/rfc8785)
canonical JSON of a projection of the spec, with ` + "`behaviorDigest`" + ` and
` + "`contentDigest`" + ` themselves elided — a hash cannot cover itself.

RFC 8785 is what makes key order, whitespace, unicode escaping and float
formatting stop mattering. It renders ` + "`1.0`" + ` and ` + "`1`" + ` identically, which is
load-bearing: the API server decodes integral JSON numbers as ` + "`int64`" + ` and
everything else as ` + "`float64`" + `, then re-encodes on the way out. Without a
canonicaliser in the path, a manifest would fail its own verification the moment
it was read back out of etcd. ` + "`TestDigestSurvivesTheAPIServer`" + ` proves it does not.

The projection is built field by field from the map below. It never marshals the
Go struct. That is the structural defence against a specific accident: if the
projection came from ` + "`json.Marshal`" + `, then adding ` + "`omitempty`" + ` to a pointer
field — an edit that looks purely cosmetic in review — would silently change
every digest ever issued. Struct tags are not part of the digest contract.

` + "`tools`" + `, ` + "`prompts`" + ` and ` + "`judges`" + ` are sets keyed by name. The projection sorts
them before hashing, so reordering a YAML file cannot change what it identifies.
The stored object is never reordered.

## Absent versus zero

JSON canonicalisation does not decide this; the projection does.

`

const rulesTable = `
| Rule | Behaviour |
|---|---|
| ` + "`Required`" + ` | Always emitted. API validation guarantees the field is non-empty, so there is no absent case to disambiguate. |
| ` + "`DistinctZero`" + ` | Emitted whenever set, including when set to zero. An unset ` + "`temperature`" + ` takes the provider default; ` + "`temperature: 0`" + ` is greedy decoding. Collapsing the two would hide a real behavioural change. |
| ` + "`EmptyIsAbsent`" + ` | An empty value normalises away. ` + "`tools: []`" + ` and an absent ` + "`tools`" + ` describe the same agent. |

## The classification map

This table is generated from ` + "`internal/digest/classify.go`" + `.
` + "`TestRegistryIsExhaustive`" + ` walks the Go type and fails if any field is missing
from it, so a field cannot reach the API without a decision being recorded here.

The guiding principle is **when in doubt, include**. Including a behaviourally
irrelevant field costs one unnecessary canary. Excluding a behaviourally
relevant one ships an unvalidated change to production.

`

const trailer = "" + `
## Trust model: attested versus asserted

The manifest's integrity guarantee is not uniform, and a compliance reader is
entitled to know exactly where the line falls.

| Class | Fields | What actually holds |
|---|---|---|
| **Attested** | ` + "`code.image@sha256:…`" + ` | Self-verifying. The hash pins the bytes and anyone with the registry can check it independently. |
| **Asserted** | ` + "`prompts[].digest`" + `, ` + "`tools[].contractDigest`" + `, ` + "`policy.bundleDigest`" + `, ` + "`retrieval.indexSnapshot`" + `, ` + "`judges[].rubricDigest`" + `, ` + "`judges[].calibration.goldSetDigest`" + ` | The referenced content lives elsewhere. Admission cannot verify it. |

So the honest claim is: **the digests attest that this set of assertions has not
changed.** They do not attest that the referenced content is what it claims to
be. "We pinned the bytes" and "we hashed a number someone typed" are different
claims, and this document will not blur them.

Closing the gap is future work, and named as such. Contract-drift detection
verifies ` + "`tools[].contractDigest`" + ` against the live server at replay time. A later
` + "`waveoff verify --resolve`" + ` can fetch and check prompt and policy content out of
band.

## What the digests do not cover

` + "`contentDigest`" + ` covers ` + "`spec`" + `. It does not cover ` + "`metadata`" + `.

That matters as soon as approver identity or a change-ticket reference is
attached to a release. Annotations under ` + "`waveoff.ai/evidence.`" + ` are therefore
frozen by the admission webhook: they may be added, never changed or removed.

This freeze is weaker than spec immutability, and the difference is worth stating
plainly. Spec immutability is a CEL rule on the CRD, so it holds even when the
webhook is down. The evidence freeze cannot be: root-level
` + "`x-kubernetes-validations`" + ` expressions can reference only ` + "`metadata.name`" + ` and
` + "`metadata.generateName`" + `, and referencing ` + "`metadata.annotations`" + ` is a compile
error that makes the API server refuse to install the CRD. So the evidence
freeze holds only while the webhook is reachable — which is one more reason the
webhook runs with ` + "`failurePolicy: Fail`" + `.

If your evidence requirements are stronger than that, the release record is the
digest plus an external audit log, not the object.

## Why there is no ` + "`--accept-hints`" + `

MCP servers may advertise ` + "`readOnlyHint`" + `, ` + "`destructiveHint`" + ` and
` + "`idempotentHint`" + ` alongside each tool. ` + "`waveoff pin`" + ` renders them as a comment
next to the blank ` + "`effect`" + ` field, and there is deliberately no flag to promote
them to values.

Those annotations come from the MCP server. The server is the untrusted party in
the tool-poisoning threat model this manifest exists to detect. Letting a server
classify its own blast radius behind a convenience flag inverts the fail-closed
rule that makes ` + "`effect`" + ` mandatory in the first place.

This is an omission, not an oversight. If the flag is ever added it must record
provenance — ` + "`effect: read`" + ` alongside ` + "`effectSource: server-hint | operator`" + ` —
so that a security review can separate what an operator asserted from what a
server claimed.

## Naming

` + "`metadata.name`" + ` is ` + "`<spec.agent>-<behaviorDigest[:12]>`" + `.

Twelve hex characters is 48 bits, not the 28 that a seven-character prefix
gives. Git went through this expansion under collision pressure; there is no
reason to start where it started rather than where it ended up.

There are two distinct collisions, and both are handled:

1. **Same ` + "`behaviorDigest`" + `, different ` + "`contentDigest`" + `** — the registry
   migration. The canonical name collides but both objects must exist, so the
   second legal form is
   ` + "`<agent>-<behavior[:12]>.<content[:8]>`" + `. Admission accepts either.
2. **Different ` + "`behaviorDigest`" + ` sharing a prefix** — vanishingly unlikely at 48
   bits, but it must not surface as a bare ` + "`AlreadyExists`" + `. ` + "`waveoff pin`" + ` and
   ` + "`waveoff verify`" + ` detect the clash and report both full digests.
`

func main() {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString(rulesTable)

	b.WriteString("| Field | In `behaviorDigest` | Absent/zero | Why |\n|---|---|---|---|\n")
	for _, f := range digest.Registry {
		in := "yes"
		if f.Inclusion == digest.ContentOnly {
			in = "**no**"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | `%s` | %s |\n",
			f.Path, in, nullName(f.Null), oneLine(f.Why)))
	}
	b.WriteString(trailer)

	if err := os.WriteFile("docs/digest.md", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("wrote docs/digest.md")
}

func nullName(n digest.NullSemantics) string {
	switch n {
	case digest.Required:
		return "Required"
	case digest.DistinctZero:
		return "DistinctZero"
	default:
		return "EmptyIsAbsent"
	}
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
