apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: waveoff-manager
  namespace: waveoff-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: waveoff
      app.kubernetes.io/component: manager
