apiVersion: v1
kind: Service
metadata:
  name: waveoff-webhook
  namespace: waveoff-system
  labels:
    app.kubernetes.io/name: waveoff
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: webhook
  selector:
    app.kubernetes.io/name: waveoff
    app.kubernetes.io/component: manager
