// Copyright 2026 The Waveoff Authors.
// SPDX-License-Identifier: Apache-2.0

package pin

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/waveoffai/waveoff/internal/digest"
)

// Emit writes the manifest as YAML with TODO comments on everything pin refused
// to guess.
//
// Digests are written only when the manifest is complete. A digest over a spec
// that still has an unresolved effect is a hash of something that cannot be
// applied, and emitting one invites somebody to trust it. When TODOs remain,
// the blessed path to a digest is `waveoff verify --write`, which is the same
// path CI and the pre-commit hook use.
func (r *Result) Emit(w io.Writer) error {
	if r.TODOs == 0 {
		b, c, err := digest.Both(&r.Manifest.Spec)
		if err != nil {
			return err
		}
		r.Manifest.Spec.BehaviorDigest = b
		r.Manifest.Spec.ContentDigest = c
		r.Manifest.Name = digest.Name(r.Manifest.Spec.Agent, b)
	} else {
		r.Manifest.Name = r.Manifest.Spec.Agent + "-unpinned"
	}

	// Route through JSON: the Kubernetes types carry json tags, and yaml.v3
	// would otherwise lowercase every field name and emit the whole of
	// ObjectMeta. YAML is a superset of JSON, so the result re-parses into a
	// node tree that can be commented.
	raw, err := json.Marshal(r.Manifest)
	if err != nil {
		return err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return err
	}
	blockStyle(&doc)
	r.annotate(&doc)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}

	if _, err := w.Write(buf.Bytes()); err != nil {
		return err
	}
	_, err = io.WriteString(w, r.stubs())
	return err
}

func (r *Result) annotate(doc *yaml.Node) {
	root := doc
	if root.Kind == yaml.DocumentNode && len(root.Content) > 0 {
		root = root.Content[0]
	}
	spec := child(root, "spec")
	if spec == nil {
		return
	}

	if r.TODOs > 0 {
		root.HeadComment = strings.TrimSpace(`
Generated by waveoff pin. NOT READY TO APPLY.

The TODOs below are fields waveoff cannot determine safely. Resolve them, then
run:

    waveoff verify --write <this file>

which computes both digests and the object name. Admission will reject this
manifest until they are correct.`)
	}

	if n := child(spec, "behaviorDigest"); n != nil && n.Value == "" {
		n.LineComment = "TODO: waveoff verify --write"
	}
	if n := child(spec, "contentDigest"); n != nil && n.Value == "" {
		n.LineComment = "TODO: waveoff verify --write"
	}
	if n := child(spec, "model"); n != nil {
		for _, key := range []string{"provider", "id"} {
			if c := child(n, key); c != nil && c.Value == "" {
				c.LineComment = "TODO: could not be read from the Deployment environment"
			}
		}
	}

	tools := child(spec, "tools")
	if tools == nil || tools.Kind != yaml.SequenceNode {
		return
	}
	for _, item := range tools.Content {
		nameNode := child(item, "name")
		effect := child(item, "effect")
		if nameNode == nil || effect == nil || effect.Value != "" {
			continue
		}
		effect.LineComment = "TODO: read | idempotent-write | write"
		// The explanation belongs on the key, not the value: yaml.v3 emits a
		// value's head comment after the line it describes.
		if k := childKey(item, "effect"); k != nil {
			k.HeadComment = r.effectComment(nameNode.Value)
		}
	}
}

// effectComment explains why the effect is blank and renders the server's own
// hints without adopting them.
func (r *Result) effectComment(tool string) string {
	lines := []string{
		"effect is mandatory and must be asserted by you, not by the server.",
		"An unclassified tool is refused during replay rather than passed through,",
		"so a tool nobody has classified can never write during an evaluation.",
	}
	c, ok := r.Contracts[tool]
	if !ok {
		return strings.Join(lines, "\n")
	}
	if suggestion, has := c.Tool.SuggestedEffect(); has {
		lines = append(lines,
			"",
			fmt.Sprintf("The server advertises hints suggesting: %s", suggestion),
			"These are the server's claims about itself. The server is the untrusted",
			"party in the tool-poisoning threat model, so waveoff will not adopt them",
			"for you. Copy the value in only if you agree with it.")
	} else {
		lines = append(lines, "", "The server advertises no hints for this tool.")
	}
	return strings.Join(lines, "\n")
}

// stubs appends commented-out sections for the parts of a manifest that do not
// live in a Deployment at all. Showing the shape is the difference between an
// operator filling them in and an operator not knowing they exist.
func (r *Result) stubs() string {
	var b strings.Builder
	spec := &r.Manifest.Spec

	if spec.Retrieval == nil {
		b.WriteString(`
#  retrieval:
#    # An unpinned index means last week's evaluation ran against a different
#    # corpus than this week's, and nothing will tell you.
#    indexSnapshot: snap-2026-08-19T04:00Z
#    embeddingModel: voyage-3
`)
	}
	if spec.Policy == nil {
		b.WriteString(`
#  policy:
#    bundleDigest: sha256:...   # OPA / Cedar bundle governing what the agent may do
`)
	}
	if len(spec.Judges) == 0 {
		b.WriteString(`
#  judges:
#    # If you gate a release on a judge, the judge is part of the release.
#    # A silent judge model update is a release-blocking change disguised as a no-op.
#    - name: task-completion
#      model: claude-opus-5
#      rubricDigest: sha256:...
#      calibration:
#        kappa: 0.71              # agreement with the human gold set
#        goldSetDigest: sha256:...
#        measuredAt: 2026-08-01T00:00:00Z
`)
	}
	return b.String()
}

// blockStyle strips the flow style that comes back from parsing JSON, so the
// output reads as YAML a person would write rather than as JSON with different
// punctuation.
func blockStyle(n *yaml.Node) {
	n.Style = 0
	for _, c := range n.Content {
		blockStyle(c)
	}
}

// childKey returns the key node for a mapping entry, which is where yaml.v3
// wants a head comment to hang.
func childKey(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i]
		}
	}
	return nil
}

func child(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}
